# Generated by Django 4.2 on 2023-04-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=155)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unity', models.CharField(max_length=100)),
                ('qty_output', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('appartment', models.CharField(max_length=20)),
                ('exit_coupon', models.IntegerField()),
                ('construction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='application.constructionsite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unity', models.CharField(max_length=100)),
                ('initial_stock', models.IntegerField()),
                ('qty_input', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                #('numeroCon',models.IntegerField()),
                #('bonrecept',models.CharField(max_length=100)),
                #('comments',models.CharField(max_length=100)),
                ('construction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='application.constructionsite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inputs', to='application.product')),
            ],
        ),
    ]
