# Generated by Django 4.2 on 2023-04-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input',
            options={'permissions': [('export_inputs', 'Can export inputs')]},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'permissions': [('export_outputs', 'Can export outputs')]},
        ),
    ]
