# Generated by Django 4.2 on 2023-05-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_constructionsite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='bonrecept',
            field=models.CharField(max_length=100, null=True, verbose_name='Bon de Réception'),
        ),
        migrations.AddField(
            model_name='input',
            name='comments',
            field=models.CharField(max_length=100, null=True, verbose_name='Commentaires'),
        ),
        migrations.AddField(
            model_name='input',
            name='numeroCon',
            field=models.IntegerField(null=True, verbose_name='Numéro de Contenaire'),
        ),
        migrations.AddField(
            model_name='product',
            name='stinitial',
            field=models.IntegerField(null=True, verbose_name='Stock Initial'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='input',
            name='initial_stock',
            field=models.IntegerField(verbose_name='Stock Initial'),
        ),
        migrations.AlterField(
            model_name='input',
            name='qty_input',
            field=models.IntegerField(verbose_name='Quantité entrée'),
        ),
        migrations.AlterField(
            model_name='input',
            name='source',
            field=models.CharField(max_length=100, verbose_name='Provenance'),
        ),
        migrations.AlterField(
            model_name='input',
            name='unity',
            field=models.CharField(max_length=100, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='output',
            name='appartment',
            field=models.CharField(max_length=20, verbose_name='Appartement'),
        ),
        migrations.AlterField(
            model_name='output',
            name='exit_coupon',
            field=models.IntegerField(verbose_name='N° BON DE SORTIE'),
        ),
        migrations.AlterField(
            model_name='output',
            name='level',
            field=models.CharField(max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='output',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='output',
            name='qty_output',
            field=models.IntegerField(verbose_name='Quantité sortie'),
        ),
        migrations.AlterField(
            model_name='output',
            name='unity',
            field=models.CharField(max_length=100, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
    ]
