# Generated by Django 4.2 on 2023-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_input_initial_stock_alter_product_stinitial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='initial_stock',
            field=models.IntegerField(null=True, verbose_name='Stock Initial'),
        ),
    ]
