# Generated by Django 4.2 on 2023-05-06 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_input_initial_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='initial_stock',
        ),
        migrations.CreateModel(
            name='ConstructionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructionsite_permission', models.ManyToManyField(to='application.constructionsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
